// Copyright (c) 2017 GreenWerx.org.
//Licensed under CPAL 1.0,  See license.txt  or go to http://greenwerx.org/docs/license.txt  for full license details.
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GreenWerx.Models.Events
{
    //http://www.quartz-scheduler.net/
    //http://quartznet.sourceforge.net/apidoc/2.0/html/

    /// <summary>
    /// Notifications are generated by alerts and are logged
    /// </summary>
    [Table("Notifications")]
    public class Notification : Node, INode
    {
        public Notification()
        {
            UUIDType = "Notification";
        }

        public DateTime? DateFirstViewed { get; set; }

        public DateTime? DateLastViewed { get; set; }

        //class name of the generating system.
        public string FromType { get; set; }

        //i.e. ReminderUUID, <whateverElseCanGenerateNotifications>.UUID
        [StringLength(32)]
        public string FromUUID { get; set; }

        public bool MarkedAsUnread { get; set; }
    }
}